/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./src/context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
}

export interface NexusGenObjects {
  Mutation: {};
  Query: {};
  Share: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: string; // ID!
    invitedEmail: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  User: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    email: string; // String!
    googleUserId: string; // String!
    id: string; // ID!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  ValueObject: { // root type
    amount?: number | null; // Int
    currency?: string | null; // String
  }
  Wish: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description?: string | null; // String
    id: string; // ID!
    image?: string | null; // String
    link?: string | null; // String
    quantity: number; // Int!
    title: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  WishList: { // root type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    headline: string; // String!
    id: string; // ID!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Mutation: { // field return type
    createUser: NexusGenRootTypes['User'] | null; // User
    createWishList: NexusGenRootTypes['WishList'] | null; // WishList
  }
  Query: { // field return type
    getCurrentUser: NexusGenRootTypes['User'] | null; // User
    getOwnWishList: NexusGenRootTypes['WishList'] | null; // WishList
    getOwnWishLists: Array<NexusGenRootTypes['WishList'] | null> | null; // [WishList]
  }
  Share: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    id: string; // ID!
    invitedEmail: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    wishList: NexusGenRootTypes['WishList']; // WishList!
  }
  User: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    email: string; // String!
    googleUserId: string; // String!
    id: string; // ID!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
  }
  ValueObject: { // field return type
    amount: number | null; // Int
    currency: string | null; // String
  }
  Wish: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description: string | null; // String
    id: string; // ID!
    image: string | null; // String
    link: string | null; // String
    price: NexusGenRootTypes['ValueObject'] | null; // ValueObject
    quantity: number; // Int!
    title: string; // String!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    wishList: NexusGenRootTypes['WishList'] | null; // WishList
  }
  WishList: { // field return type
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    headline: string; // String!
    id: string; // ID!
    shares: NexusGenRootTypes['Share'][]; // [Share!]!
    updatedAt: NexusGenScalars['DateTime']; // DateTime!
    user: NexusGenRootTypes['User']; // User!
    wishes: NexusGenRootTypes['Wish'][]; // [Wish!]!
  }
}

export interface NexusGenFieldTypeNames {
  Mutation: { // field return type name
    createUser: 'User'
    createWishList: 'WishList'
  }
  Query: { // field return type name
    getCurrentUser: 'User'
    getOwnWishList: 'WishList'
    getOwnWishLists: 'WishList'
  }
  Share: { // field return type name
    createdAt: 'DateTime'
    id: 'ID'
    invitedEmail: 'String'
    updatedAt: 'DateTime'
    wishList: 'WishList'
  }
  User: { // field return type name
    createdAt: 'DateTime'
    email: 'String'
    googleUserId: 'String'
    id: 'ID'
    updatedAt: 'DateTime'
  }
  ValueObject: { // field return type name
    amount: 'Int'
    currency: 'String'
  }
  Wish: { // field return type name
    createdAt: 'DateTime'
    description: 'String'
    id: 'ID'
    image: 'String'
    link: 'String'
    price: 'ValueObject'
    quantity: 'Int'
    title: 'String'
    updatedAt: 'DateTime'
    wishList: 'WishList'
  }
  WishList: { // field return type name
    createdAt: 'DateTime'
    headline: 'String'
    id: 'ID'
    shares: 'Share'
    updatedAt: 'DateTime'
    user: 'User'
    wishes: 'Wish'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createUser: { // args
      email: string; // String!
    }
    createWishList: { // args
      headline: string; // String!
    }
  }
  Query: {
    getOwnWishList: { // args
      id: string; // String!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}