service: best-wishes-api

plugins:
  - serverless-offline

custom:
  serverless-offline:
    stages:
      - local
    port: 3001

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'local'}
  region: eu-west-2
  profile: best-wishes-api
  environment: ${file(./serverless.env.yml):${opt:stage, 'local'}}

functions:
  app:
    handler: src/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
